"""Writes tests/fixtures/sun-positions.json: the reference solar positions the Swift SunEngine must reproduce.

Locations are city centres used as arbitrary test inputs, not properties. Run from engine/: python3 scripts/make_sun_fixture.py
"""

import calendar
import json
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from lightreplay import sun  # noqa: E402

LOCATIONS = {
    "melbourne": (-37.8136, 144.9631),
    "sydney": (-33.8688, 151.2093),
    "darwin": (-12.4634, 130.8456),
    "hobart": (-42.8821, 147.3272),
    "london": (51.4779, 0.0),
    "reykjavik": (64.1466, -21.9426),
}


def main():
    start = calendar.timegm((2026, 1, 1, 0, 0, 0))
    points = []
    for name, (lat, lon) in LOCATIONS.items():
        for day in range(0, 365, 23):
            for hour in range(0, 24, 3):
                t = start + day * 86400 + hour * 3600 + 17 * 60   # off the hour so minutes are exercised
                p = sun.position(t, lat, lon)
                a_az, a_el = sun.almanac_position(t, lat, lon)
                points.append({
                    "location": name, "unix": t, "lat": lat, "lon": lon,
                    "azimuth_deg": p.azimuth_deg, "elevation_deg": p.elevation_deg,
                    "true_elevation_deg": p.true_elevation_deg, "declination_deg": p.declination_deg,
                    "equation_of_time_min": p.equation_of_time_min,
                    "almanac_azimuth_deg": a_az, "almanac_elevation_deg": a_el,
                })
    out = Path(__file__).resolve().parents[1] / "tests" / "fixtures" / "sun-positions.json"
    lines = ",\n".join("  " + json.dumps(p, separators=(",", ":")) for p in points)
    out.write_text('{"algorithm":"noaa-meeus + spa-refraction (P 1010 hPa, T 10 C)",\n'
                   '"note":"synthetic test inputs; generated by engine/scripts/make_sun_fixture.py",\n'
                   f'"points":[\n{lines}\n]}}\n', encoding="utf-8")
    print(f"{len(points)} points -> {out}")


if __name__ == "__main__":
    main()
